custom_topic_sort_order_items:
  description: "Set up the Custom Topic Sort Order Menu Items."
  type: objects
  default: 
    [
      { "icon": clock, "label": js.activity, "action": activity },
      { "icon": calendar, "label": js.created, "action": created },
      { "icon": comments, "label": js.posts, "action": posts },
      { "icon": heart, "label": js.likes, "action": likes },
      { "icon": eye, "label": js.views, "action": views },
    ]
  schema:
    name: item
    identifier: action
    properties:
      icon:
        type: string
      label:
        type: string
        required: true
      action:
        type: enum
        choices:
          - activity
          - created
          - posts
          - likes
          - views

custom_topic_sort_order_button_icon: 
  default: "sort"
  type: "string"
  description: "Change the topic sort order button icon."
hide_label_on_mobile: 
  default: true
  type: "bool"
  description: "Hide the topic sort order button label."
ascending_icon: 
  default: "arrow-down-wide-short"
  type: "string"
  description: "Change the item ascending icon."
descending_icon: 
  default: "arrow-down-short-wide"
  type: "string"
  description: "Change the item descending icon."
svg_icons: 
  default: "sort|arrow-down-short-wide|arrow-down-wide-short|calendar"
  type: "list"
  list_type: "compact"
  description: "List of FontAwesome 6 icons used in this theme component"
